name: simple_cached_future_builder
description: A simplified FutureBuilder with basic caching abilities to not fetch new data on each rebuild.
version: 0.1.1
homepage: https://github.com/ArvidNy/simple_cached_future_builder
issue_tracker: https://github.com/ArvidNy/simple_cached_future_builder/issues
screenshots:
  - description: 'This GIF shows how the data easily can be cached using this package.'
    path: overview.gif
topics:
  - network
  - futurebuilder
  - cache

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.0